Run Migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -167,6 +167,32 @@ jobs:
           template: success_tagged_deploy_1
       # Here's where you will add some code to rollback on failure 
 
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+              cd backend
+              npm install
+            # Run and save the migration output
+              npm run migrations > migrations_dump.txt
+              exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+               if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+               then
+             # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+                        curl https://kvdb.io/HJEsjfEikkKe3JyFZ4NCN5/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                fi
+                exit 1
+     # Here's where you will add some code to rollback on failure 
+
 
  
 
